### ISSUE TITLE
Run create_dataset.py

### ISSUE THREAD

**Issue by sarmadm** [robsanpam/CK-Plus#1]
Hi 

Could you please help , is below command to run is right ?

python create_dataset.py ~/C:/Users//PyProjects/ckp/  ~/C:/Users//PyProjects/ckp/FACS_labels/ ~/C:/Users/PyProjects/ckp/ckpcohn-kanade-images/ ~/C:/Users/PyProjects/ckp/emotion_images/  True 0 9 3 112 112

**Comment by robsanpam** [comment]
Are you using Windows? I developed this code to work with Ubuntu, so I am not sure if the string paths are supposed to be written that way in Windows.

**Comment by sarmadm** [comment]
yes , im using windows anaconda env

**Comment by sarmadm** [comment]
Now when I run train.py this error shows : 


`Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    main(sys.argv[1:])
  File "train.py", line 225, in main
    emotions_dir = str(argv[0])
IndexError: list index out of range`

**Comment by robsanpam** [comment]
Try removing the "~/" from the beginning of your paths when you run the script. Also, I notice that you have some double slashes ( // ) on your paths which you must replace with single ones ( / ).
