### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by dmjeong1995** [robsanpam/CK-Plus#2]
Hi

Your codes are really helpful
by the way, this error is occured while running train.py
when the index1 is 0, im's shape is (3,112,112,3)
but it is changed when index1 is not 0
it is changed (1, 128, 128, 3)

and
in newly created ~/ckp/emotion_images/ directories,
0 labeled folders and others have different size

**(43, 3, 112, 112, 3) #X.shape
(3, 112, 112, 3) #im.shape
Recovering arrays for label 1
~/ckp/emotion_images_3frames/1/S010_004.npy
im shape: (1, 128, 128, 3) #im.shape**
Traceback (most recent call last):
  File "train.py", line 320, in <module>
    main(sys.argv[1:])
  File "train.py", line 244, in main
    X, y = recover_3darrays(emotions_dir, neutral_instances=neutral_instances)
  File "train.py", line 64, in recover_3darrays
    X = np.append(X, [im], axis=0)
  File "C:\Users\IVPL-SERVER\Anaconda3\envs\fer3\lib\site-packages\numpy\lib\function_base.py", line 5152, in append
    return concatenate((arr, values), axis=axis)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

bolds are print result

could you please help me? and thank you in advance.

**Comment by dmjeong1995** [comment]
I made emotion_images wrong. I solved this problem. :-)
